os: linux
language: python
dist: focal

matrix:
  include:
    # These are quick and often catch errors, so list them first
    - python: 3.6
      env: CHECK_DOCS=1
    - python: 3.6
      env: CHECK_FORMATTING=1
    # The pypy tests are slow, so we list them first
    - python: pypy3.6-7.2.0
      dist: bionic
    # Uncomment if you want to test on pypy nightly:
    # - language: generic
    #   env: PYPY_NIGHTLY_BRANCH=py3.6
    - python: 3.6
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - python: 3.9-dev
    - os: osx
      language: generic
      env: MACPYTHON=3.6.6
    - os: osx
      language: generic
      env: MACPYTHON=3.7.0

script:
  - ci/travis.sh
